program: src/exam_project/train.py
name: sweep_lr_and_batch_size
project: mlops_project
entity: s204654-danmarks-tekniske-universitet-dtu
method: bayes
metric:
  goal: maximize
  name: val_accuracy
parameters:
  lr:
    min: 0.0001
    max: 0.1
    distribution: log_uniform_values
  batch-size:
    values: [16, 32, 64, 128]

run_cap: 20
