program: src/exam_project/train.py
name: sweep_skin_cancer_model
project: mlops_project
entity: s204654-danmarks-tekniske-universitet-dtu
method: bayes
metric:
  goal: maximize
  name: val_accuracy
parameters:
  lr:
    min: 0.0001
    max: 0.1
    distribution: log_uniform


run_cap: 10