name: DVC Workflow

on:
  pull_request:
    branches:
    - [main , master]
    paths:
    - '**/data/raw/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        make dev_requirements
        pip list

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Pull data
      run: |
        dvc pull --no-run-cache

    #- name: Check data statistics
    #  run: |
    #    python src/exam_project/dataset_statistics.py

    - name: Check data statistics & generate report
      run: |
        python src/exam_project/dataset_statistics.py > data_statistics.md
        echo '![](./train_label_distribution.png "Train label distribution")' >> data_statistics.md
        echo '![](./test_label_distribution.png "Test label distribution")' >> data_statistics.md

    - name: Preprocess data and push to GCP
      run: |
        python src/exam_project/data.py
        dvc push

    #- name: Setup cml
    #  uses: iterative/setup-cml@v2

    - name: Comment on PR
      env:
        REPO_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        cml comment create data_statistics.md --watermark-title="Data Checker" # (1)!
